---
title: Queer/Trans Zinefest 2023
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Queer & Trans Zinefest (QTZ) is an annual small works festival celebrating
  the creations of queer, trans, and gender non-conforming artists. This year, we
  welcome 50 exhibitors from RI and beyond to the The Steel Yard in Providence, RI
  on Saturday, September 2, from 11am-5pm. Come join us! QTZ is totally free and open
  to the public.
permalink: pretty
Background Color: "#FFE0DE"
Text Color: "#00347A"
Favicon Image: "/uploads/favicon.ico"
Text Logo Sideways Image: 
Text Logo Stacked Image: 
Mascot Image: "/uploads/Better-Sabii-QTZ-2023-Animation.gif"
Event Date: 
Tagline: 
