---
title: Queer/Trans Zinefest 2023
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Queer & Trans Zinefest (QTZ) is an annual small works festival celebrating
  the creations of queer, trans, and gender non-conforming artists. This year, we
  welcome 50 exhibitors from RI and beyond to the The Steel Yard in Providence, RI
  on Saturday, September 2, from 11am-5pm. Come join us! QTZ is totally free and open
  to the public.
permalink: pretty
background_color: "#FFE0DE"
text_color: "#00347A"
accent_color: "#ff413a"
Favicon Image: "/uploads/favicon.ico"
Text Logo Sideways Image: 
Text Logo Stacked Image: "/uploads/QTZ-2023-Font-Final-2_darker_flat.png"
Text Logo Alt Text: QTZ 2023 Logo
Mascot Image: "/uploads/Better-Sabii-QTZ-2023-Animation.gif"
Mascot Alt Text: An animation of the QTZ 2023 jaunty peach mascot walking with a spring
  in their step.
Event Date: 
Tagline: Queer/Trans Zinefest in Providence, RI on Saturday September 2, 2023
apply_button_image: "/uploads/Asset%202@4x-8.png"
Apply Button Link: https://airtable.com/shrka8iYZ0YZUuG8a
Mascot Icon Image: "/uploads/Sabii_QTZ-2023-Peach-Mascot-Animationv2_solidbg.gif"
